### ISSUE TITLE
sensu::client_service failure when cookbook > 0.6.0 (opsworks)

### ISSUE THREAD

**Issue by heffergm** [sensu/sensu-chef#231]
So sometime after the cookbook rev'd past 0.6.0, I started seeing the stack trace below.

I managed to track down the problem to this commit: 720fa2e0114c715cdf1f3389aafb7b4cbf3b6821
Having reverted it, sensu::client_service runs without issue.

```
[2014-01-26T12:17:12+00:00] DEBUG: Re-raising exception: Chef::Exceptions::ValidationFailed - sensu_service[sensu-client] (sensu::client_service line 20) had an error: Chef::Exceptions::ValidationFailed: Required argument service is missing!
/opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/mixin/params_validate.rb:113:in `_pv_required'
  /opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/mixin/params_validate.rb:69:in `send'
  /opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/mixin/params_validate.rb:69:in `validate'
  /opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/mixin/params_validate.rb:66:in `each'
  /opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/mixin/params_validate.rb:66:in `validate'
  /opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/mixin/params_validate.rb:56:in `each'
  /opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/mixin/params_validate.rb:56:in `validate'
  /opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/mixin/params_validate.rb:88:in `set_or_return'
  /opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/resource/lwrp_base.rb:86:in `_set_or_return_service'
  /opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/resource/lwrp_base.rb:80:in `service'
  /opt/aws/opsworks/releases/20131222191101_216/site-cookbooks/sensu/providers/service.rb:33:in `load_current_resource'
  /opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/provider.rb:97:in `run_action'
  /opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/resource.rb:617:in `run_action'
  /opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/runner.rb:50:in `run_action'
  /opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/runner.rb:82:in `converge'
  /opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/runner.rb:82:in `each'
  /opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/runner.rb:82:in `converge'
  /opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/resource_collection.rb:94:in `execute_each_resource'
  /opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
  /opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
  /opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
  /opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
  /opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
  /opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/resource_collection.rb:92:in `execute_each_resource'
  /opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/runner.rb:81:in `converge'
  /opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/client.rb:404:in `converge'
  /opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/client.rb:469:in `do_run'
  /opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/client.rb:200:in `run'
  /opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/application.rb:190:in `run_chef_client'
  /opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/application/solo.rb:239:in `run_application'
  /opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/application/solo.rb:231:in `loop'
  /opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/application/solo.rb:231:in `run_application'
  /opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/application.rb:73:in `run'
  /opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/chef-solo:25
  /opt/aws/opsworks/current/bin/chef-solo:16:in `load'
  /opt/aws/opsworks/current/bin/chef-solo:16
[2014-01-26T12:17:12+00:00] ERROR: Running exception handlers
[2014-01-26T12:17:12+00:00] ERROR: Exception handlers complete
[2014-01-26T12:17:12+00:00] FATAL: Stacktrace dumped to /opt/aws/opsworks/releases/20131222191101_216/chef-stacktrace.out
[2014-01-26T12:17:12+00:00] DEBUG: Chef::Exceptions::ValidationFailed: sensu_service[sensu-client] (sensu::client_service line 20) had an error: Chef::Exceptions::ValidationFailed: Required argument service is missing!
/opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/mixin/params_validate.rb:113:in `_pv_required'
/opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/mixin/params_validate.rb:69:in `send'
/opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/mixin/params_validate.rb:69:in `validate'
/opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/mixin/params_validate.rb:66:in `each'
/opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/mixin/params_validate.rb:66:in `validate'
/opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/mixin/params_validate.rb:56:in `each'
/opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/mixin/params_validate.rb:56:in `validate'
/opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/mixin/params_validate.rb:88:in `set_or_return'
/opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/resource/lwrp_base.rb:86:in `_set_or_return_service'
/opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/resource/lwrp_base.rb:80:in `service'
/opt/aws/opsworks/releases/20131222191101_216/site-cookbooks/sensu/providers/service.rb:33:in `load_current_resource'
/opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/provider.rb:97:in `run_action'
/opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/resource.rb:617:in `run_action'
/opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/runner.rb:50:in `run_action'
/opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/runner.rb:82:in `converge'
/opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/runner.rb:82:in `each'
/opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/runner.rb:82:in `converge'
/opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/resource_collection.rb:94:in `execute_each_resource'
/opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/resource_collection.rb:92:in `execute_each_resource'
/opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/runner.rb:81:in `converge'
/opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/client.rb:404:in `converge'
/opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/client.rb:469:in `do_run'
/opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/client.rb:200:in `run'
/opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/application.rb:190:in `run_chef_client'
/opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/application/solo.rb:239:in `run_application'
/opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/application/solo.rb:231:in `loop'
/opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/application/solo.rb:231:in `run_application'
/opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/application.rb:73:in `run'
/opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/chef-solo:25
/opt/aws/opsworks/current/bin/chef-solo:16:in `load'
/opt/aws/opsworks/current/bin/chef-solo:16
[2014-01-26T12:17:12+00:00] FATAL: Chef::Exceptions::ValidationFailed: sensu_service[sensu-client] (sensu::client_service line 20) had an error: Chef::Exceptions::ValidationFailed: Required argument service is missing!
pid 25125 exited with status 256, exit code: 1 (time=11 sec)
[2014-01-26 12:17:12] ERROR [opsworks-agent (25122)] Chef run failed with exitcode 1
```

**Comment by cwjohnston** [comment]
Closing due to age of issue referencing a very old version of Chef. Please open a new issue if this is still an issue.
