### ISSUE TITLE
WARN: Cloning resource attributes

### ISSUE THREAD

**Issue by runningman84** [sensu/sensu-chef#355]
Chef 12.x prints warning messages:
```
       [2015-07-03T09:52:13+00:00] WARN: Cloning resource attributes for rabbitmq_user[sensu] from prior resource (CHEF-3694)
       [2015-07-03T09:52:13+00:00] WARN: Previous rabbitmq_user[sensu]: /tmp/kitchen/cookbooks/sensu/definitions/rabbitmq_credentials.rb:6:in `block in from_file'
       [2015-07-03T09:52:13+00:00] WARN: Current  rabbitmq_user[sensu]: /tmp/kitchen/cookbooks/sensu/definitions/rabbitmq_credentials.rb:11:in `block in from_file'
       [2015-07-03T09:52:13+00:00] WARN: Cloning resource attributes for apt_repository[sensu] from prior resource (CHEF-3694)
       [2015-07-03T09:52:13+00:00] WARN: Previous apt_repository[sensu]: /tmp/kitchen/cookbooks/sensu/recipes/_linux.rb:26:in `from_file'
       [2015-07-03T09:52:13+00:00] WARN: Current  apt_repository[sensu]: /tmp/kitchen/cookbooks/uchiwa/recipes/repo.rb:30:in `from_file'
```

**Comment by cwjohnston** [comment]
In my experience these warnings are quite common and rarely indicative of an actual problem. There are some efforts under way (e.g. https://github.com/chef/chef-rfc/issues/76) to address the problems raised in [CHEF-3694](http://tickets.chef.io/browse/CHEF-3694) but at this time there's no clear path to move forward on addressing resource cloning. Closing as wontfix (for now).
