### ISSUE TITLE
NetFX3 feature install fails on Server 2012 R2

### ISSUE THREAD

**Issue by drpebcak** [sensu/sensu-chef#362]
https://github.com/sensu/sensu-chef/blob/master/recipes/_windows.rb#L41

```
  * windows_feature[NetFx3ServerFeatures] action install[2015-07-22T14:04:21-07:
00] INFO: Processing windows_feature[NetFx3ServerFeatures] action install (sensu
::_windows line 36)
 (up to date)
  * windows_feature[NetFx3] action install[2015-07-22T14:04:23-07:00] INFO: Proc
essing windows_feature[NetFx3] action install (sensu::_windows line 41)


    ============================================================================
====
    Error executing action `install` on resource 'windows_feature[NetFx3]'
    ============================================================================
====

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0, 42, 127, 3010], but received '-2146498298'

    ---- Begin output of C:\Windows\sysnative\dism.exe /online /enable-feature /
featurename:NetFx3 /norestart   ----
    STDOUT: Deployment Image Servicing and Management tool
    Version: 6.3.9600.17031

    Image Version: 6.3.9600.17031

    Enabling feature(s)

    Error: 0x800f0906

    The source files could not be downloaded.
    Use the "source" option to specify the location of the files that are requir
ed to restore the feature. For more information on specifying a source location,
 see http://go.microsoft.com/fwlink/?LinkId=243077.

    The DISM log file can be found at C:\Windows\Logs\DISM\dism.log
    STDERR:
    ---- End output of C:\Windows\sysnative\dism.exe /online /enable-feature /fe
aturename:NetFx3 /norestart   ----
    Ran C:\Windows\sysnative\dism.exe /online /enable-feature /featurename:NetFx
3 /norestart   returned -2146498298

    Cookbook Trace:
    ---------------
    c:/chef/cache/cookbooks/windows/providers/feature_dism.rb:28:in `install_fea
ture'
    c:/chef/cache/cookbooks/windows/libraries/feature_base.rb:8:in `action_insta
ll'

    Resource Declaration:
    ---------------------
    # In c:/chef/cache/cookbooks/sensu/recipes/_windows.rb

     41: windows_feature "NetFx3" do
     42:   source node.sensu.windows.dism_source
     43: end
     44:

    Compiled Resource:
    ------------------
    # Declared in c:/chef/cache/cookbooks/sensu/recipes/_windows.rb:41:in `from_
file'

    windows_feature("NetFx3") do
      provider LWRP provider windows_feature_dism from cookbook windows
      action :install
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :windows_feature
      cookbook_name "sensu"
      recipe_name "_windows"
      feature_name "NetFx3"
    end

[2015-07-22T14:04:28-07:00] INFO: Running queued delayed notifications before re
-raising exception

Running handlers:
[2015-07-22T14:04:28-07:00] ERROR: Running exception handlers
Running handlers complete
[2015-07-22T14:04:28-07:00] ERROR: Exception handlers complete
Chef Client failed. 6 resources updated in 109.854377 seconds
[2015-07-22T14:04:28-07:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stack
trace.out
[2015-07-22T14:04:28-07:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: windows
_feature[NetFx3] (sensu::_windows line 41) had an error: Mixlib::ShellOut::Shell
CommandFailed: Expected process to exit with [0, 42, 127, 3010], but received '-
2146498298'
---- Begin output of C:\Windows\sysnative\dism.exe /online /enable-feature /feat
urename:NetFx3 /norestart   ----
STDOUT: Deployment Image Servicing and Management tool
Version: 6.3.9600.17031

Image Version: 6.3.9600.17031

Enabling feature(s)

Error: 0x800f0906

The source files could not be downloaded.
Use the "source" option to specify the location of the files that are required t
o restore the feature. For more information on specifying a source location, see
 http://go.microsoft.com/fwlink/?LinkId=243077.

The DISM log file can be found at C:\Windows\Logs\DISM\dism.log
STDERR:
---- End output of C:\Windows\sysnative\dism.exe /online /enable-feature /featur
ename:NetFx3 /norestart   ----
Ran C:\Windows\sysnative\dism.exe /online /enable-feature /featurename:NetFx3 /n
orestart   returned -2146498298
```

**Comment by portertech** [comment]
Looks like you need to specify a install source/location:

https://github.com/sensu/sensu-chef/blob/master/attributes/default.rb#L10
https://github.com/sensu/sensu-chef/blob/master/recipes/_windows.rb#L37

**Comment by drpebcak** [comment]
@portertech I don't need to do that for 2008 R2 - and indeed, what would I use as an install source? Shouldn't that package be available online? For a server in aws, I don't have any install media or anything like that. It's just the netfx3 part that fails anyway. I found some articles talking about workarounds for not being able to install .net features, but I don't have any of the relevant kbs installed.

**Comment by ajeba99** [comment]
@portertech
Running the powershell commend "Install-WindowsFeature Net-Framework-Core" resolved the issue for me.  That installs dotnet 3.5 on windows 2012r2

**Comment by drpebcak** [comment]
This doesn't work for me, but I am beginning to suspect there is something wrong with my install of Server 2012r2. I'm going to close this issue because the evidence suggests it _should_ work.
