### ISSUE TITLE
Chef warning property options is declared in two resources

### ISSUE THREAD

**Issue by runningman84** [sensu/sensu-chef#405]
I got these errors lately:
```
       [2016-02-12T09:25:12+00:00] WARN: /tmp/kitchen/cache/cookbooks/sensu/providers/gem.rb:4:in `block (2 levels) in class_from_file': property version is declared in both gem_package[ohai] and #<#<Class:0x0000000479c1c0>:0x0000000c63e168>. Use new_resource.version instead. At /tmp/kitchen/cache/cookbooks/sensu/providers/gem.rb:4:in `block (2 levels) in class_from_file'
       [2016-02-12T09:25:12+00:00] WARN: /tmp/kitchen/cache/cookbooks/sensu/providers/gem.rb:5:in `block (2 levels) in class_from_file': property options is declared in both gem_package[ohai] and #<#<Class:0x0000000479c1c0>:0x0000000c63e168>. Use new_resource.options instead. At /tmp/kitchen/cache/cookbooks/sensu/providers/gem.rb:5:in `block (2 levels) in class_from_file'
````

**Comment by cwjohnston** [comment]
Hi @runningman84, under which version of Chef are you seeing this warning?

**Comment by tombin** [comment]
I am also seeing this on chef 12.

**Comment by runningman84** [comment]
This is another warning in Chef 12.8
```
         * sensu_gem[sensu-plugins-network-checks] action install[2016-03-10T11:12:46+00:00] WARN: /tmp/kitchen/cache/cookbooks/sensu/providers/gem.rb:5:in `block (2 levels) in class_from_file': property options is declared in both gem_package[sensu-plugins-network-checks] and #<#<Class:0x00000004502068>:0x00000006673238>. Use new_resource.options instead. At /tmp/kitchen/cache/cookbooks/sensu/providers/gem.rb:5:in `block (2 levels) in class_from_file'
        (up to date)
```

**Comment by cwjohnston** [comment]
I can't tell from changelog what version of chef contains the fix for this issue, but it appears to be an upstream bug that has been fixed: https://github.com/chef/chef/pull/4684
