### ISSUE TITLE
Rabbit mq fails start after enabling admin plugin

### ISSUE THREAD

**Issue by devilldog** [sensu/sensu-chef#460]
All, Installing sensu on a somewhat distributed environment, just rabbitmq on separate host. it installs fine and it starts, then installs the admin plugin and fails to restart. This is RHEL 7.1 with 2.12.0 version of the cookbook.

``` 
* service[rabbitmq-server] action start                                                                [393/4993]
    - start service service[rabbitmq-server]
Recipe: rabbitmq::mgmt_console
  * rabbitmq_plugin[rabbitmq_management] action enable
    * execute[rabbitmq-plugins enable rabbitmq_management] action run
      - execute rabbitmq-plugins enable rabbitmq_management

Recipe: rabbitmq::default
  * service[rabbitmq-server] action restart

    ================================================================================
    Error executing action `restart` on resource 'service[rabbitmq-server]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /sbin/service rabbitmq-server restart ----
    STDOUT: Restarting rabbitmq-server (via systemctl):  [FAILED]
    STDERR: Job for rabbitmq-server.service failed because the control process exited with error code. See "systemc
tl status rabbitmq-server.service" and "journalctl -xe" for details.
    ---- End output of /sbin/service rabbitmq-server restart ----
    Ran /sbin/service rabbitmq-server restart returned 1

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:49:in `block in ru
n_action'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:47:in `each'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:47:in `run_action'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/rabbitmq/recipes/default.rb

    225:   service node['rabbitmq']['service_name'] do
    226:     action [:enable, :start]
    227:     supports :status => true, :restart => true
    228:     provider Chef::Provider::Service::Upstart if node['rabbitmq']['job_control'] == 'upstart'
    229:     provider Chef::Provider::Service::Init if node['rabbitmq']['job_control'] == 'init'
    230:   end
    231: else

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/rabbitmq/recipes/default.rb:225:in `from_file'

    service("rabbitmq-server") do
      action [:enable, :start]
      updated true
      supports {:status=>true, :restart=>true}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      service_name "rabbitmq-server"
      enabled true
      running true
      pattern "rabbitmq-server"
      declared_type :service
      cookbook_name "rabbitmq"
      recipe_name "default"
    end
```

**Comment by devilldog** [comment]
Here is the out put from startup
```
Jun 30 13:48:59 LXXXXX01 rabbitmq-server[19847]: Stopping rabbitmq-server: RabbitMQ is not running
Jun 30 13:48:59 LXXXXX01 rabbitmq-server[19847]: rabbitmq-server.
Jun 30 13:48:59 LXXXXX01 systemd[1]: Stopped LSB: Enable AMQP service provided by RabbitMQ broker.
-- Subject: Unit rabbitmq-server.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit rabbitmq-server.service has finished shutting down.
Jun 30 13:48:59 LXXXXX01 polkitd[743]: Unregistered Authentication Agent for unix-process:19842:180970377 (s
Jun 30 13:48:59 LXXXXX01 polkitd[743]: Registered Authentication Agent for unix-process:20074:180970433 (sys
Jun 30 13:48:59 LXXXXX01 systemd[1]: Starting LSB: Enable AMQP service provided by RabbitMQ broker...
-- Subject: Unit rabbitmq-server.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit rabbitmq-server.service has begun starting up.
Jun 30 13:48:59 LXXXXX01 su[20169]: (to rabbitmq) root on none
Jun 30 13:48:59 LXXXXX01 su[20169]: pam_unix(su:session): session opened for user rabbitmq by (uid=0)
Jun 30 13:48:59 LXXXXX01 su[20169]: pam_unix(su:session): session closed for user rabbitmq
Jun 30 13:48:59 LXXXXX01 su[20319]: (to rabbitmq) root on none
Jun 30 13:48:59 LXXXXX01 su[20319]: pam_unix(su:session): session opened for user rabbitmq by (uid=0)
Jun 30 13:48:59 LXXXXX01 su[20321]: (to rabbitmq) root on none
Jun 30 13:48:59 LXXXXX01 su[20321]: pam_unix(su:session): session opened for user rabbitmq by (uid=0)
Jun 30 13:49:03 LXXXXX01 auditd[572]: Audit daemon rotating log files
Jun 30 13:49:05 LXXXXX01 su[20321]: pam_unix(su:session): session closed for user rabbitmq
Jun 30 13:49:05 LXXXXX01 rabbitmq-server[20079]: Starting rabbitmq-server: SUCCESS
Jun 30 13:49:05 LXXXXX01 rabbitmq-server[20079]: rabbitmq-server.
Jun 30 13:49:05 LXXXXX01 systemd[1]: Started LSB: Enable AMQP service provided by RabbitMQ broker.
-- Subject: Unit rabbitmq-server.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit rabbitmq-server.service has finished starting up.
--
-- The start-up result is done.

```

**Comment by cwjohnston** [comment]
@devilldog thanks for opening this issue but I believe the error you are encountering is occurring outside the scope of this cookbook. For now I'm going to close this issue, but feel free to open another if you find there's behavior in this cookbook which is at the root of the issue.
