### ISSUE TITLE
Warning property source is declared in both resources

### ISSUE THREAD

**Issue by runningman84** [sensu/sensu-chef#490]
I get a lot of warnings like this
```
[2016-09-02T09:25:47+00:00] WARN: /var/chef/cache/cookbooks/sensu/providers/gem.rb:5:in `block (2 levels) in class_from_file': property source is declared in both gem_package[ohai] and #<#<Class:0x0000000486ea58>:0x00000006a08678>. Use new_resource.source instead. At /var/chef/cache/cookbooks/sensu/providers/gem.rb:5:in `block (2 levels) in class_from_file'
[2016-09-02T09:25:47+00:00] WARN: /var/chef/cache/cookbooks/sensu/providers/gem.rb:6:in `block (2 levels) in class_from_file': property options is declared in both gem_package[ohai] and #<#<Class:0x0000000486ea58>:0x00000006a08678>. Use new_resource.options instead. At /var/chef/cache/cookbooks/sensu/providers/gem.rb:6:in `block (2 levels) in class_from_file'
```

**Comment by cwjohnston** [comment]
Searching around shows [other cookbooks](https://travis-ci.org/socrata-cookbooks/x2go-server) produce similar warnings when they implement a resource of their own with a `source` property.

@tas50 any ideas as to the source of this? I'm not super concerned as it seems to be a spurious warning but it would be cool to eliminate more of these 😄

**Comment by tas50** [comment]
That seems to just be a bogus warning message
